### ISSUE TITLE
Install error piranhaGUI v1.5.3

### ISSUE THREAD

**Issue by CatherineTroman** [CorwinAnsley/artifice#29]
I was doing a fresh install of piranhaGUI on a new Windows laptop. It popped up with the following error when I first clicked on the desktop shortcut:

![Screenshot 2023-11-17 172407](https://github.com/CorwinAnsley/artifice/assets/77683415/63a063b8-1cda-41eb-bfd0-fb69c8de1ec5)

I tried uninstalling, deleting the .exe and starting again but got the same error again. I successfully installed the previous version (v1.5.1) so not sure if it is something specific in the latest release that has gone wrong?

**Comment by CorwinAnsley** [comment]
Hi Catherine I pushed a quick fix to that, the windows download for that release should work properly now
